### ISSUE TITLE
[Question] Move existing documentation

### ISSUE THREAD

**Issue by codeliner** [zendframework/documentation#2]
Hi,

I've read the documentation contribution guide but one question is left open: How to move existing documentation from https://github.com/zendframework/zf2-documentation to the component?

Does it make sense to do it manually or do you provide a script?

**Comment by GeeH** [comment]
I've actually got a script which I've used with Authentication. However, I've hit a small brick wall that I'm trying to navigate around. I've set aside some time this week to progress this and you should see some movement soon.

G

**Comment by codeliner** [comment]
Great news! Thx for the update.
