### ISSUE TITLE
Documentation layout on each component's landing page

### ISSUE THREAD

**Issue by poisa** [zendframework/documentation#4]
First of all I'm looking at the new docs and "wow!", way to go! Having contributed a few pull requests to the framework itself I realize this has been a massive undertaking! Congrats to all the team! 

One thing that in my opinion would make for a much better UX is the difference between the docs for the Cache component and the Component Installer. 

https://docs.zendframework.com/zend-cache/

https://docs.zendframework.com/zend-component-installer/ 

In the Zend Cache page, there is no data, only the composer command. It looks empty and the first few times I saw the page I thought the docs for that component hadn't been completed. I then thought, "I'm sure they could have copied over the previous docs as the contents are surely not that different in this version". I went back to the page and looking at the top bar, I now saw that the navigation bar contained what I was looking for. Instead, in the Zend Component Installer, it's all immediately available right there, no extra clicks.

I think it would be a great idea that the landing page for each component have the contents of the top menu laid out tree-like (think sitemap links). For example, in the Zend Cache page you could have:
- Storage
  - Adapters
  - Capabilities
  - Plugins
- Cache Patterns
  - Introduction
  - CallbackCache
  - etc, etc...

I'm sure this could be automated so that it auto updates as the docs are recompiled. 

Going one step further -and this is also something that could probably be automated-, another plus would be to be able to have the whole docs for a component in one single page (like the logged in version of Instructables). Sometimes you are looking for that little bit of syntax in the docs and having it all in one page could make browser searches trivial. Not to mention that this would be a nice benefit for those of us who sometimes work tethered to the phone or with an intermittent internet connection; we could just download one page and have the whole component's doc readily available. 

Just my 2 cents!

**Comment by froschdesign** [comment]
@poisa 
> I think it would be a great idea that the landing page for each component have the contents of the top menu laid out tree-like (think sitemap links).

I agree, because many people overlook the navigation top-bar. It's not the best solution and [problematic](https://github.com/zendframework/zf-mkdoc-theme/issues/22).
A table of contents on the home page would help definite.

> I'm sure this could be automated so that it auto updates as the docs are recompiled.

A complete new page in theme is needed, I will test it.

> Going one step further -and this is also something that could probably be automated-, another plus would be to be able to have the whole docs for a component in one single page

This will not work with the current and the next versions of [MkDocs](http://www.mkdocs.org/), because this feature is not planned.

**Comment by froschdesign** [comment]
@poisa 
Please look at: https://github.com/zendframework/zf-mkdoc-theme/pull/34

**Comment by poisa** [comment]
@froschdesign I really like it!

**Comment by settermjd** [comment]
@froschdesign, looks great. A definite improvement.
