### ISSUE TITLE
Selection highlight has insufficient contrast (black on black) in code examples

### ISSUE THREAD

**Issue by Chealer** [zendframework/documentation#5]
Through a ::selection selector, the selections in the reference are highlighted with a black background rather than the usual blue, at least in Firefox. Since black is also used for backgrounds in code examples, there is minimal contrast between selected and non-selected text, unless that text contains non-white parts (there is still a certain contrast, since the background of examples is not completely black).

For example, in https://docs.zendframework.com/zend-validator/messages/ selecting " Zend\Validator\GreaterThan" in the third code sample is more difficult because you hardly see where the selection starts and ends.

This could be solved by using the default highlight color, at least for examples.

**Comment by froschdesign** [comment]
@weierophinney 
Can be closed, because zendframework/zf-mkdoc-theme#25 was merged.

**Comment by Chealer** [comment]
I do not see the fix in production, but according to my read the fix seems valid.

**Comment by froschdesign** [comment]
@Chealer 
Please test here: https://docs.zendframework.com/zend-problem-details/intro/

**Comment by Chealer** [comment]
Done, confirmed fixed.
Thank you @froschdesign
