### ISSUE TITLE
Can we use this repository for documentation-related questions and for project planning?

### ISSUE THREAD

**Issue by froschdesign** [zendframework/documentation#6]
@weierophinney 
My suggestion is to convert this repository and remove all outdated files, then we could use this repository for general documentation issues and project planning. (This means we need write access. 😉)

**Comment by froschdesign** [comment]
ping @weierophinney 

I have some ideas to improve the documentation, but these ideas do not refer to a single component or on the layout. I think, this repository could be the right place.

## Example

We should add a notice to the documentation if a class needs another component which is not installed by Composer because it is _not strictly required_.

### zend-validator

```json
"suggest": {
    "zendframework/zend-db": "Zend\\Db component, required by the (No)RecordExists validator",
    "zendframework/zend-filter": "Zend\\Filter component, required by the Digits validator",
    "zendframework/zend-i18n": "Zend\\I18n component to allow translation of validation error messages",
    "zendframework/zend-math": "Zend\\Math component, required by the Csrf validator",
    "zendframework/zend-i18n-resources": "Translations of validator messages",
    "zendframework/zend-servicemanager": "Zend\\ServiceManager component to allow using the ValidatorPluginManager and validator chains",
    "zendframework/zend-session": "Zend\\Session component, ^2.8; required by the Csrf validator",
    "zendframework/zend-uri": "Zend\\Uri component, required by the Uri and Sitemap\\Loc validators"
},
```

https://github.com/zendframework/zend-validator/blob/87e743d11d49a157011a49a962c25e7a11adc7c5/composer.json#L34-L43

- zendframework/zend-validator#83
- zendframework/zend-validator#221
- zendframework/zend-validator#222

### zend-paginator

https://github.com/zendframework/zend-paginator/blob/b4e853ef104101069e781f50f662f514e4e4e33f/composer.json#L36-L43

### zend-mail

https://github.com/zendframework/zend-mail/blob/0e43bfe8994f38b2c7a2c560b1dcfee6eaaabc37/composer.json#L33-L36

### …

**Comment by settermjd** [comment]
Hey @froschdesign, I think your idea makes a lot of sense. What say you @weierophinney?

**Comment by weierophinney** [comment]
I've added both @froschdesign and @settermjd to the Documentation team, and given @froschdesign the role of Maintainer (allowing him to add members to the team); all members have write access to the repositories assigned to the team. I've also changed the repos managed by that team to include:

- this repository
- the "tutorials" repository
- the "zf-mkdoc-theme" repository

Go ahead and start making changes!
